BEGIN TRANSACTION;

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    telephone TEXT UNIQUE
);

CREATE TABLE posts(
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    message TEXT NOT NULL,
    media_url VARCHAR(100),
    user_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE commentaries(
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    message TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY(post_id) REFERENCES posts(id)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

COMMIT;
